#!/usr/bin/env node
// 构建期脚本：将 public/ 下所有静态资源内联为 base64 常量，写入 embedded-assets.js
// 目的：让 pkg 把它们随 require 链一起打进单文件 exe，运行时从内存直接读取，不依赖外部文件。
const fs = require('fs');
const path = require('path');

const PUBLIC = path.join(__dirname, 'public');
const OUT = path.join(__dirname, 'embedded-assets.js');

function walk(dir, rel, map) {
  for (const name of fs.readdirSync(dir)) {
    const p = path.join(dir, name);
    const st = fs.statSync(p);
    const r = rel ? rel + '/' + name : name;
    if (st.isDirectory()) walk(p, r, map);
    else map['/' + r] = fs.readFileSync(p).toString('base64');
  }
}

const assets = {};
walk(PUBLIC, '', assets);
const content =
  '// AUTO-GENERATED by build-assets.js — do not edit manually\n' +
  'module.exports = ' + JSON.stringify(assets) + ';\n';
fs.writeFileSync(OUT, content);
console.log('[build-assets] generated embedded-assets.js: ' +
  Object.keys(assets).length + ' files, ' + content.length + ' bytes');
